# Use the official Microsoft Node.js devcontainer image
# FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:20
FROM mcr.microsoft.com/devcontainers/javascript-node:20

# install git and docker-cli
# RUN apt-get update && apt-get install -y git docker.io && rm -rf /var/lib/apt/lists/*

# Switch to non-root (the image already has 'node' user)
# USER root
