services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspaces:cached
    networks:
      - example_net
    depends_on:
      - firestore-emulator

networks:
  example_net:
    external: false
